name: Lint, Format and Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js LTS
        uses: actions/setup-node@v1
        with:
          node-version: 18.x
      - name: Install dependencies
        run: npm ci
      - name: Run validate script
        run: npm run validate
